ongr_elasticsearch:
    source_directories: [/src/Document]
    indexes:
        App\Document\Playback:
            hosts: ['%env(resolve:ELASTICSEARCH_URL)%']
        App\Document\Playlist:
            hosts: ['%env(resolve:ELASTICSEARCH_URL)%']
        App\Document\Song:
            hosts: ['%env(resolve:ELASTICSEARCH_URL)%']
            settings:
                analysis:
                    filter:
                        romaji_readingform:
                            type: kuromoji_readingform
                            use_romaji: true

                        katakana_readingform:
                            type: kuromoji_readingform
                            use_romaji: true
                    analyzer:
                        romaji_analyzer:
                            type: custom
                            tokenizer: kuromoji_tokenizer
                            filter:
                                - romaji_readingform

                        katakana_analyzer:
                            type: custom
                            tokenizer: kuromoji_tokenizer
                            filter:
                                - katakana_readingform
